### ISSUE TITLE
`else return;` in `index.js` line 15 causes webpack failed to load this file.

### ISSUE THREAD

**Issue by sunziping2016** [buddys/qq-wechat-emotion-parser#1]
With `webpack`, it seems the `else returns;` is invalid in the import stage, though it never gets executed.

    ERROR in ./~/qq-wechat-emotion-parser/src/index.js
    Module parse failed: /some/path/to/node_modules/qq-wechat-emotion-
    parser/src/index.js 'return' outside of function (15:5)
    You may need an appropriate loader to handle this file type.
    |     window.qqWechatEmotionParser = qqWechatEmotionParser;
    | }
    | else return;
    | 
    | function build(){
     @ ./src/components/message-content-parser.js 10:0-61
     @ ./src/components/index.jsx
     @ ./src/wall/wall.jsx
     @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/wall/wall.jsx

Commenting the statements out can fix this. I recommend to use a better fallback.

**Comment by harttle** [comment]
seems like a linting problem, thankyou for your feedback

**Comment by sunziping2016** [comment]
发现一只前端大神。关注><

**Comment by harttle** [comment]
published @1.0.3
