### ISSUE TITLE
img标签建议加上display:inline

### ISSUE THREAD

**Issue by heson525** [buddys/qq-wechat-emotion-parser#10]
建议表情作为图片不换行。
`<img style="display:inline!important;" src="https://res.wx.qq.com/mpres/htmledition/images/icon/emotion/0.gif" alt="/::)">`

**Comment by harttle** [comment]
img 是 inline 标签，一定是哪里的 css 设置了 block

**Comment by heson525** [comment]
> img 是 inline 标签，一定是哪里的 css 设置了 block

确实，大意了。感谢，顺便邀请一起催更。适配新版微信表情。
