### ISSUE TITLE
请教下如何将表情代码删除和插入并做到灵活的在任意位置添加和删除

### ISSUE THREAD

**Issue by tsuixh** [buddys/qq-wechat-emotion-parser#7]
非常感谢做出这样的一个解析的组件，非常实用。我有用你的组件实现了表情选择组件和支持表情输入的输入框组件，但在实现输入框组件的时候有一些问题想请教一下。我在添加表情的时候将表情代码替换成img标签，展现的伪文本域中，但是如何做到删除这个表情能够把对应纯文本中的表情代码删除呢？纯请教，非组件的issue，如能帮助，万分感谢！

**Comment by Meriky** [comment]
可以考虑用正则表达式，检索文本域内的图片链接，根据表情img标签内alt属性判断需要删除的表情文本，如果有多个相同的表情就使用数组索引维护。

**Comment by Meriky** [comment]
img标签内是有alt属性的，更新的时候可以用正则把img标签都替换成alt属性内的表情代码
